### ISSUE TITLE
Support union with one or more string or expression keys

### ISSUE THREAD

**Issue by crocodele** [supermetrics-public/php-ext-jsonpath#52]
Fixes for making the following tests pass:

- [x] comparison_dot_notation/020.phpt: Test dot notation after union with keys
- [ ] comparison_union/004.phpt: Test union with filter
- [x] comparison_union/003.phpt: Test union with duplication from object
- [x] comparison_union/005.phpt: Test union with keys
- [x] comparison_union/006.phpt: Test union with keys on object without key
- [x] comparison_union/007.phpt: Test union with keys after array slice
- [x] comparison_union/008.phpt: Test union with keys after bracket notation
- [x] comparison_union/009.phpt: Test union with keys after dot notation with wildcard
- [x] comparison_union/010.phpt: Test union with keys after recursive descent

**Comment by mkaminski1988** [comment]
@crocodele How important is `comparison_union/004.phpt`? It's possible to do, but would add complication to the interpreter.

**Comment by crocodele** [comment]
> How important is `comparison_union/004.phpt`? It's possible to do, but would add complication to the interpreter.

Happy to go with the exception instead there.
