### ISSUE TITLE
Fix assorted JSONPath Comparison tests, vol. 2

### ISSUE THREAD

**Issue by crocodele** [supermetrics-public/php-ext-jsonpath#64]
Fixes for making the following uncategorized tests pass:

- [x] comparison_filter/035.phpt: Test filter expression with equals number for array slice with range 1
- [x] comparison_filter/040.phpt: Test filter expression with equals object
- [x] comparison_filter/057.phpt: Test filter expression with regular expression
- [x] comparison_filter/071.phpt: Test filter expression with value from recursive descent
- [x] comparison_root/001.phpt: Test root

**Comment by crocodele** [comment]
@mkaminski1988, any opinion on the regex syntax – should we stick with quotes around the regex pattern or remove them? Personally I think the expression looks tidier without the quotes, and that's also how most implementations seem to work.

**Comment by mkaminski1988** [comment]
@crocodele, agreed. Working on support for this in #103.
